apiVersion: v1
kind: Service
metadata:
  name: longeviver-fitness-app
spec:
  type: LoadBalancer
  selector:
    app: longeviver-fitness-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
