apiVersion: apps/v1
kind: Deployment
metadata:
  name: longeviver-fitness-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longeviver-fitness-app
  template:
    metadata:
      labels:
        app: longeviver-fitness-app
    spec:
      containers:
        - name: longeviver-fitness-app
#          Primeira imagem é criada com o Git Actions e a segunda com o terraform
#          image: southamerica-east1-docker.pkg.dev/longeviver-dev-franciel/longeviverfitness-repositorio/longeviverfitness:latest
          image: southamerica-east1-docker.pkg.dev/longeviver-dev-franciel/longeviverfitness-repositorio
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: artifact-registry-secret
