apiVersion: apps/v1
kind: Deployment
metadata:
  name: longeviver-fitness-app-teste-um
spec:
  selector:
    matchLabels:
      app: gke-cloud-sql-app
  template:
    metadata:
      labels:
        app: gke-cloud-sql-app
    spec:
      serviceAccountName: longeviverfitness-service-account-sql
      containers:
        - name: gke-cloud-sql-app
          image: southamerica-east1-docker.pkg.dev/longeviver-dev-franciel/longeviverfitness-repositorio:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: INSTANCE_CONNECTION_NAME
              value: longeviver-dev-franciel:us-central1:longeviverdev
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database