apiVersion: apps/v1
kind: Deployment
metadata:
  name: longeviver-fitness-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: longeviver-fitness-app
  template:
    metadata:
      labels:
        app: longeviver-fitness-app
    spec:
      containers:
        - name: longeviver-fitness-app
          image: southamerica-east1-docker.pkg.dev/longeviverfitness/longeviverfitness-repositorio/longeviverfitness:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: artifact-registry-secret
