apiVersion: apps/v1
kind: Deployment
metadata:
  name: longeviver-gke
  namespace: ${K8S_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longeviver-gke
  template:
    metadata:
      annotations:
        iam.gke.io/gcp-service-account: ${GCP_SERVICE_ACCOUNT}
      labels:
        app: longeviver-gke
    spec:
      serviceAccountName: ${GCP_SERVICE_ACCOUNT_NAME}
      containers:
        - name: longeviver-gke
          image: ${DOCKER_IMAGE}
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: gke-cloud-sql-secrets
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gke-cloud-sql-secrets
                  key: password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: gke-cloud-sql-secrets
                  key: db_host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: gke-cloud-sql-secrets
                  key: database

      imagePullSecrets:
        - name: artifact-registry-secret