apiVersion: v1
kind: Service
metadata:
  name: longeviver-gke
  namespace: longeviver-dev-mateus-455600-namespace
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: longeviver-gke
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
