name: Deploy completo

on:
  push:
    branches:
      - main
      - feature/BARUAM-24

permissions:
  id-token: write
  contents: read

jobs:
  export-env:
    name: Export Environment Variables
    runs-on: ubuntu-latest
    steps:
      - name: Output Environment Variables
        run: |
          echo "PROJECT_ID=longeviver-dev-mateus-455600" >> GITHUB_OUTPUT
          echo "PROJECT_NUMBER=400595761684" >> GITHUB_OUTPUT
          echo "PROJECT_REGION=us-central1" >> GITHUB_OUTPUT
          echo "PROJECT_ZONE=us-central1-c" >> GITHUB_OUTPUT
          echo "BOOTSTRAP_STATE_BUCKET_NAME=lgv-terraform-bootstrap-state-mateus" >> GITHUB_OUTPUT
          echo "ARTIFACT_REGISTRY_REPOSITORY_NAME=longeviver-fitness" >> GITHUB_OUTPUT
          echo "GITHUB_REPO=Baruam-Solutions/LongeviverFitnessApi" >> GITHUB_OUTPUT
          echo "GITHUB_POOL=ghpool" >> GITHUB_OUTPUT
          echo "GITHUB_PROVIDER=github-provider" >> GITHUB_OUTPUT

  bootstrap:
    needs: export-env
    uses: ./.github/workflows/01-bootstrap-apply.yml
    with:
      TF_WORKDIR: infra/terraform/bootstrap/
      PROJECT_ID: ${{ needs.export-env.outputs.PROJECT_ID }}
      PROJECT_NUMBER: ${{ needs.export-env.outputs.PROJECT_NUMBER }}
      PROJECT_REGION: ${{ needs.export-env.outputs.PROJECT_REGION }}
      PROJECT_ZONE: ${{ needs.export-env.outputs.PROJECT_ZONE }}
      BOOTSTRAP_STATE_BUCKET_NAME: ${{ needs.export-env.outputs.BOOTSTRAP_STATE_BUCKET_NAME }}
      ARTIFACT_REGISTRY_REPOSITORY_NAME: ${{ needs.export-env.outputs.ARTIFACT_REGISTRY_REPOSITORY_NAME }}
      GITHUB_REPO: ${{ needs.export-env.outputs.GITHUB_REPO }}
      GITHUB_POOL: ${{ needs.export-env.outputs.GITHUB_POOL }}
      GITHUB_PROVIDER: ${{ needs.export-env.outputs.GITHUB_PROVIDER }}

  infra:
    needs: bootstrap
    uses: ./.github/workflows/02-infra-dev-apply.yml
    with:
      TF_WORKDIR: infra/terraform/main-resources/
      PROJECT_ID: ${{ needs.export-env.outputs.PROJECT_ID }}
      PROJECT_NUMBER: ${{ needs.export-env.outputs.PROJECT_NUMBER }}
      PROJECT_REGION: ${{ needs.export-env.outputs.PROJECT_REGION }}
      PROJECT_ZONE: ${{ needs.export-env.outputs.PROJECT_ZONE }}