name: Deploy completo

on:
  push:
    branches:
      - main
      - feature/BARUAM-24

permissions:
  id-token: write
  contents: read

# Define as vari치veis de ambiente necess치rias para o Terraform
# Para ser reconhecido pelo terraform, a vari치vel precisa estar no formato TF_VAR_<nome_da_vari치vel>
env:
  TF_VAR_PROJECT_ID:                        longeviver-dev-mateus-455600
  TF_VAR_PROJECT_NUMBER:                    400595761684
  TF_VAR_PROJECT_REGION:                    us-central1
  TF_VAR_PROJECT_ZONE:                      us-central1-c
  TF_VAR_BOOTSTRAP_STATE_BUCKET_NAME:       lgv-terraform-bootstrap-state-mateus
  TF_VAR_ARTIFACT_REGISTRY_REPOSITORY_NAME: longeviver-fitness
  TF_VAR_GITHUB_REPO:                       Baruam-Solutions/LongeviverFitnessApi
  TF_VAR_GITHUB_POOL:                       ghpool
  TF_VAR_GITHUB_PROVIDER:                   github-provider

jobs:
  bootstrap:
    uses: ./.github/workflows/01-bootstrap-apply.yml
    with:
      TF_WORKDIR: infra/terraform/bootstrap/
      TF_VAR_PROJECT_ID: longeviver-dev-mateus-455600
      TF_VAR_PROJECT_NUMBER: 400595761684
      TF_VAR_PROJECT_REGION: us-central1
      TF_VAR_PROJECT_ZONE: us-central1-c
      TF_VAR_BOOTSTRAP_STATE_BUCKET_NAME: lgv-terraform-bootstrap-state-mateus
      TF_VAR_ARTIFACT_REGISTRY_REPOSITORY_NAME: longeviver-fitness
      TF_VAR_GITHUB_REPO: Baruam-Solutions/LongeviverFitnessApi
      TF_VAR_GITHUB_POOL: ghpool
      TF_VAR_GITHUB_PROVIDER: github-provider

  infra:
    needs: bootstrap
    uses: ./.github/workflows/02-infra-dev-apply.yml
    with:
      TF_WORKDIR: infra/terraform/main-resources/
      TF_VAR_PROJECT_ID: longeviver-dev-mateus-455600
      TF_VAR_PROJECT_NUMBER: 400595761684
      TF_VAR_PROJECT_REGION: us-central1
      TF_VAR_PROJECT_ZONE: us-central1-c
