name: Deploy completo

on:
  push:
    branches:
      - feature/BARUAM-24
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente para implantar (dev, prod)'
        required: true
        type: choice
        default: dev-mateus
        options:
          - dev-mateus
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  # Job para definir o ambiente e carregar variáveis/secrets correspondentes
  setup-environment:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    outputs:
      PROJECT_ID: ${{ PROJECT_ID }}
      PROJECT_NUMBER: ${{ PROJECT_NUMBER }}
      PROJECT_REGION: ${{ PROJECT_REGION }}
      PROJECT_ZONE: ${{ PROJECT_ZONE }}
      BOOTSTRAP_STATE_BUCKET_NAME: ${{ BOOTSTRAP_STATE_BUCKET_NAME }}
      ARTIFACT_REGISTRY_REPOSITORY_NAME: ${{ ARTIFACT_REGISTRY_REPOSITORY_NAME }}
      GITHUB_REPO: ${{ GIT_REPO }}
      GITHUB_POOL: ${{ GIT_POOL }}
      GITHUB_PROVIDER: ${{ GIT_PROVIDER }}
    steps:
      - name: Debug - List all environment variables
        run: |
          echo "--- Listing all environment variables for this job ---"
          env # Comando 'env' lista todas as variáveis de ambiente
          echo "-----------------------------------------------------"
          echo "Setting up environment: ${{ github.event.inputs.environment }}"
          echo "Project ID (from env): ${{ PROJECT_ID }}"
          echo "Project Number (from env): ${{ PROJECT_NUMBER }}"
          echo "GIT_POOL (from env): ${{ GIT_POOL }}"
          echo "GIT_PROVIDER (from env): ${{ GIT_PROVIDER }}"
          echo "GIT_REPO (from env): ${{ GIT_REPO }}"
          echo "-----------------------------------------------------"

  # Job para aplicar o bootstrap com permissões para git actions WIF, state bucket e artifact registry
  bootstrap:
    needs: setup-environment
    uses: ./.github/workflows/01-bootstrap.yml
    with:
      TF_WORKDIR: infra/terraform/bootstrap/
      PROJECT_ID: ${{ needs.setup-environment.outputs.PROJECT_ID }}
      PROJECT_NUMBER: ${{ needs.setup-environment.outputs.PROJECT_NUMBER }}
      PROJECT_REGION: ${{ needs.setup-environment.outputs.PROJECT_REGION }}
      PROJECT_ZONE: ${{ needs.setup-environment.outputs.PROJECT_ZONE }}
      BOOTSTRAP_STATE_BUCKET_NAME: ${{ needs.setup-environment.outputs.BOOTSTRAP_STATE_BUCKET_NAME }}
      ARTIFACT_REGISTRY_REPOSITORY_NAME: ${{ needs.setup-environment.outputs.ARTIFACT_REGISTRY_REPOSITORY_NAME }}
      GITHUB_REPO: ${{ needs.setup-environment.outputs.GITHUB_REPO }}
      GITHUB_POOL: ${{ needs.setup-environment.outputs.GITHUB_POOL }}
      GITHUB_PROVIDER: ${{ needs.setup-environment.outputs.GITHUB_PROVIDER }}

  # Job para aplicar a infraestrutura principal
  infra:
    needs: [bootstrap, setup-environment]
    uses: ./.github/workflows/02-infra.yml
    with:
      TF_WORKDIR: infra/terraform/main-resources/
      PROJECT_ID: ${{ needs.setup-environment.outputs.PROJECT_ID }}
      PROJECT_NUMBER: ${{ needs.setup-environment.outputs.PROJECT_NUMBER }}
      GITHUB_POOL: ${{ needs.setup-environment.outputs.GITHUB_POOL }}
      GITHUB_PROVIDER: ${{ needs.setup-environment.outputs.GITHUB_PROVIDER }}
