name: Deploy completo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Escolha o ambiente para o deploy'
        required: true
        default: 'dev-mateus'
        type: choice
        options:
          - dev-mateus

permissions:
  id-token: write
  contents: read

jobs:
  # Job para aplicar o bootstrap com permissões para git actions WIF, state bucket e artifact registry
  bootstrap:
    uses: ./.github/workflows/01-bootstrap.yml
    with:
      TF_WORKDIR: infra/terraform/bootstrap/
      ENV_NAME: ${{ github.event.inputs.environment }}

  # Job para aplicar a infraestrutura principal
  infra:
    needs: [ bootstrap ]
    uses: ./.github/workflows/02-main-resources.yml
    with:
      TF_WORKDIR: infra/terraform/main-resources/
      ENV_NAME: ${{ github.event.inputs.environment }}