name: Workflow para a camada infra-dev

on:
  workflow_call:
    inputs:
      TF_WORKDIR:
        required: true
        type: string
      TF_VAR_PROJECT_ID:
        required: true
        type: string
      TF_VAR_PROJECT_NUMBER:
        required: true
        type: string
      TF_VAR_PROJECT_REGION:
        required: true
        type: string
      TF_VAR_PROJECT_ZONE:
        required: true
        type: string

# Ativa o uso de OIDC no workflow do GitHub Actions
permissions:
  id-token: write
  contents: read

jobs:
    apply-infra-dev:
        runs-on: ubuntu-latest
        steps:
          # Autenticação com Google Cloud usando Workload Identity Federation
          - id: 'auth'
            name: 'Authenticate to Google Cloud'
            uses: 'google-github-actions/auth@v0.4.0'
            with:
              workload_identity_provider: 'projects/${{ env.TF_VAR_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.TF_VAR_GITHUB_POOL }}/providers/${{ env.TF_VAR_GITHUB_PROVIDER }}'
              service_account: 'github-actions-sa@${{ env.TF_VAR_PROJECT_ID }}.iam.gserviceaccount.com'
              audience: 'https://iam.googleapis.com/projects/${{ env.TF_VAR_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.TF_VAR_GITHUB_POOL }}/providers/${{ env.TF_VAR_GITHUB_PROVIDER }}'