name: Workflow para a camada infra-dev

on:
  workflow_call:
    inputs:
      TF_WORKDIR:
        required: true
        type: string
      PROJECT_ID:
        required: true
        type: string
      PROJECT_NUMBER:
        required: true
        type: string
      PROJECT_REGION:
        required: true
        type: string
      PROJECT_ZONE:
        required: true
        type: string

# Ativa o uso de OIDC no workflow do GitHub Actions
permissions:
  id-token: write
  contents: read

jobs:
  apply-infra-dev:
    runs-on: ubuntu-latest
    steps:
      # Checkout do código
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Debug Workload Identity Provider Inputs
        run: |
          echo "PROJECT_NUMBER: ${{ inputs.PROJECT_NUMBER }}"
          echo "GITHUB_POOL: ${{ inputs.GITHUB_POOL }}"
          echo "GITHUB_PROVIDER: ${{ inputs.GITHUB_PROVIDER }}"
          echo "Constructed WIF Provider: projects/${{ inputs.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ inputs.GITHUB_POOL }}/providers/${{ inputs.GITHUB_PROVIDER }}"

      # Autenticação com Google Cloud usando Workload Identity Federation
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ inputs.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ inputs.GITHUB_POOL }}/providers/${{ inputs.GITHUB_PROVIDER }}'
          service_account: 'github-actions-sa@${{ inputs.PROJECT_ID }}.iam.gserviceaccount.com'
#          audience: 'https://iam.googleapis.com/projects/${{ inputs.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ inputs.GITHUB_POOL }}/providers/${{ inputs.GITHUB_PROVIDER }}'