name: Workflow para a camada de Kubernetes

on:
  workflow_call:
    inputs:
      TF_WORKDIR:
        required: true
        type: string
      ENV_NAME:
        required: true
        type: string
      K8S_SERVICE_ACCOUNT_EMAIL:
        required: true
        type: string
      K8S_ENDPOINT: 
        required: true
        type: string
      K8S_CERTIFICATE_AUTHORITY:
        required: true
        type: string
      K8S_SERVICE_ACCOUNT_NAME:
        required: true
        type: string
    secrets:
      TF_VAR_DB_USERNAME:
        required: true
      TF_VAR_DB_PASSWORD:
        required: true
    outputs:
      k8s_namespace:
        description: "Namespace do Kubernetes"
        value: ${{ jobs.apply.outputs.tf_k8s_namespace }}

# Ativa o uso de OIDC no workflow do GitHub Actions
permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV_NAME }}
    env:
      TF_VAR_PROJECT_ID: ${{ vars.TF_VAR_PROJECT_ID }}
      TF_VAR_PROJECT_REGION: ${{ vars.TF_VAR_PROJECT_REGION }}
      TF_VAR_PROJECT_ZONE: ${{ vars.TF_VAR_PROJECT_ZONE }}
      TF_VAR_DATABASE: ${{ vars.TF_VAR_DATABASE }}
      TF_VAR_DB_USERNAME: ${{ secrets.TF_VAR_DB_USERNAME }}
      TF_VAR_DB_PASSWORD: ${{ secrets.TF_VAR_DB_PASSWORD }}
      TF_VAR_K8S_ENDPOINT: ${{ inputs.K8S_ENDPOINT }}
      TF_VAR_K8S_CERTIFICATE_AUTHORITY: ${{ inputs.K8S_CERTIFICATE_AUTHORITY }}

    steps:
      # Checkout do código
      - name: Checkout source code
        uses: actions/checkout@v4

      # Autenticação com Google Cloud usando Workload Identity Federation
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ vars.TF_VAR_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ vars.TF_VAR_GIT_POOL }}/providers/${{ vars.TF_VAR_GIT_PROVIDER }}'
          service_account: 'github-actions-sa@${{ vars.TF_VAR_PROJECT_ID }}.iam.gserviceaccount.com'

      - name: Decode K8s Service Account details
        run: |
          # Decodifica o email e exporta como variável de ambiente
          DECODED_EMAIL=$(echo "${{ inputs.K8S_SERVICE_ACCOUNT_EMAIL }}" | base64 --decode)
          echo "TF_VAR_K8S_SERVICE_ACCOUNT_EMAIL=${DECODED_EMAIL}" >> $GITHUB_ENV

          # Decodifica o nome da Service Account e exporta como variável de ambiente
          DECODED_NAME=$(echo "${{ inputs.K8S_SERVICE_ACCOUNT_NAME }}" | base64 --decode)
          echo "TF_VAR_K8S_SERVICE_ACCOUNT_NAME=${DECODED_NAME}" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        run: |
          cd ${{ inputs.TF_WORKDIR }}
          terraform init

      - name: Terraform Validate
        run: |
          cd ${{ inputs.TF_WORKDIR }}
          terraform validate

      - name: Terraform Plan
        run: |
          cd ${{ inputs.TF_WORKDIR }}
          terraform plan -out=tfplan

      - name: Terraform Apply
        run: |
          cd ${{ inputs.TF_WORKDIR }}
          terraform apply -auto-approve tfplan

      - name: Terraform Outputs
        working-directory: ${{ inputs.TF_WORKDIR }}
        id: get_outputs # Adiciona um ID ao passo para capturar o output
        run: |
          K8S_NAMESPACE=$(terraform output -raw k8s_namespace | base64 -w 0)
          echo "tf_k8s_namespace=${K8S_NAMESPACE}" >> $GITHUB_OUTPUT

    outputs:
      tf_k8s_namespace: ${{ steps.get_outputs.outputs.tf_k8s_namespace }}