name: Workflow para teste, build e push de imagens Docker
on:
  workflow_call:
    inputs:
      ENV_NAME:
        required: true
        type: string

# Ativa o uso de OIDC no workflow do GitHub Actions
permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV_NAME }}
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache de Dependências Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Rodar Testes com Maven
        run: mvn test

      - name: Construir Aplicação com Maven
        run: mvn clean install -DskipTests=true

      # Configura o ambiente para o Docker Buildx e, por padrão, cria um builder com um driver que suporta os recursos avançados de cache
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construir Imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true # Carregar a imagem no daemon Docker local
          tags: ${{ vars.TF_VAR_PROJECT_REGION }}-docker.pkg.dev/${{ vars.TF_VAR_PROJECT_ID }}/${{ vars.TF_VAR_ARTIFACT_REGISTRY_REPOSITORY_NAME }}/longeviver:${{ github.sha }}
          cache-from: type=gha # Habilita o cache de camadas do GitHub Actions
          cache-to: type=gha,mode=max # Salva o cache para futuras execuções

      # Autenticação com Google Cloud usando Workload Identity Federation
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ vars.TF_VAR_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ vars.TF_VAR_GIT_POOL }}/providers/${{ vars.TF_VAR_GIT_PROVIDER }}'
          service_account: 'github-actions-sa@${{ vars.TF_VAR_PROJECT_ID }}.iam.gserviceaccount.com'

      # Configurar Docker para usar gcloud como helper de credenciais
      - name: Configure Docker with Artifact Registry
        run: gcloud auth configure-docker ${{ vars.TF_VAR_PROJECT_REGION }}-docker.pkg.dev

      # Push da imagem Docker
      - name: Push Docker image
        run: |
          docker push ${{ vars.TF_VAR_PROJECT_REGION }}-docker.pkg.dev/${{ vars.TF_VAR_PROJECT_ID }}/${{ vars.TF_VAR_ARTIFACT_REGISTRY_REPOSITORY_NAME }}/longeviver:${{ github.sha }}