name: Deploy to Google Kubernetes Engine

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.GKE_CONTAINER_REGISTRY }}/longeviverfitness:latest .

      - name: Login to Artifact Registry
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | gcloud auth activate-service-account --key-file=/dev/stdin
          gcloud auth configure-docker ${{ secrets.GKE_CONTAINER_REGISTRY }} --quiet

      - name: Push Docker image
        run: |
          docker push ${{ secrets.GKE_CONTAINER_REGISTRY }}/longeviverfitness:latest

      - name: Set up GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_CLUSTER_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to GKE
        env:
          IMAGE: ${{ secrets.GKE_CONTAINER_REGISTRY }}/longeviverfitness:latest
        run: |
          kubectl apply -f k8s/
