#https://cloud.google.com/blog/products/identity-security/enabling-keyless-authentication-from-github-actions
name: Deploy to Google Kubernetes Engine with Workload Identity Federation

on:
  push:
    branches:
      - main
      - feature/BARUAM-24

# Ativa o uso de OIDC no workflow do GitHub Actions
permissions:
  id-token: write
  contents: read

env:
  TF_WORKDIR:       infra/terraform/
  GKE_CLUSTER_NAME: longeviverfitness-cluster
  GKE_CLUSTER_ZONE: us-central1-c
  GCP_PROJECT_ID:   longeviver-dev-mateus-455600

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout source code
        uses: actions/checkout@v3

      # Autenticação com Google Cloud usando Workload Identity Federation
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/400595761684/locations/global/workloadIdentityPools/githubpool/providers/github-provider'
          service_account: 'github-actions-sa@longeviver-dev-mateus-455600.iam.gserviceaccount.com'
          audience: 'https://iam.googleapis.com/projects/400595761684/locations/global/workloadIdentityPools/githubpool/providers/github-provider'

      # Configurar Docker para usar gcloud como helper de credenciais
      - name: Configure Docker with Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # Build da imagem Docker
      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/longeviver-dev-mateus-455600/longeviverfitness-repositorio/longeviverfitness:latest .

      # Push da imagem Docker
      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/longeviver-dev-mateus-455600/longeviverfitness-repositorio/longeviverfitness:latest

      - name: Set up GKE credentials
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER_NAME --zone $GKE_CLUSTER_ZONE --project $GCP_PROJECT_ID

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        run: |
          cd $TF_WORKDIR
          terraform init

      - name: Terraform Validate
        run:  |
          cd $TF_WORKDIR
          terraform validate

      - name: Terraform Plan
        run:  |
          cd $TF_WORKDIR
          terraform plan -out=tfplan

      - name: Terraform Apply
        run: |
          cd $TF_WORKDIR
          terraform apply -auto-approve tfplan